window.compliments = [
    "You have a captivating smile.",
    "Your hair looks stunning today.",
    "You have a great sense of humor.",
    "Your creativity knows no bounds.",
    "You have a contagious energy that lifts everyone around you.",
    "Your kindness is inspiring.",
    "Your intelligence is truly impressive.",
    "You have a voice that could soothe the soul.",
    "Your sense of style is impeccable.",
    "Your dedication to your work is admirable.",
    "You have a way of making people feel seen and heard.",
    "Your determination is inspiring.",
    "Your presence fills the room with positivity.",
    "You have a heart of gold.",
    "Your thoughtfulness is appreciated more than you know.",
    "Your loyalty is unwavering.",
    "You have a natural talent for making others feel comfortable.",
    "Your confidence is magnetic.",
    "Your patience is a virtue.",
    "You have a unique perspective that is truly valuable.",
    "Your hard work pays off in spades.",
    "Your passion is infectious.",
    "You have a radiant spirit that shines bright.",
    "Your generosity knows no bounds.",
    "Your attention to detail is remarkable.",
    "Your intuition is impressive.",
    "Your empathy is a gift to those around you.",
    "You have a refreshing honesty that is rare.",
    "Your positive attitude is contagious.",
    "Your optimism is inspiring.",
    "You have a calming presence that eases any situation.",
    "Your adaptability is impressive.",
    "Your intelligence is matched only by your kindness.",
    "Your resilience is remarkable.",
    "You have a wonderful way of bringing people together.",
    "Your determination is unwavering.",
    "Your smile lights up the room.",
    "You have an incredible sense of humor that brightens everyone's day.",
    "Your confidence is infectious.",
    "Your passion for life is inspiring.",
    "Your empathy is a true gift to those around you.",
    "Your curiosity is contagious.",
    "You have a natural ability to lead.",
    "Your creativity is truly awe-inspiring.",
    "You have a wonderful sense of style.",
    "Your dedication to your craft is admirable.",
    "Your hard work is paying off in spades.",
    "Your loyalty is unwavering.",
    "Your attention to detail is truly remarkable.",
    "You have a unique perspective that is truly valuable.",
    "Your intuition is impressive.",
    "Your generosity knows no bounds.",
    "You have a natural talent for bringing people together.",
    "Your presence is truly uplifting.",
    "Your positive attitude is infectious.",
    "Your optimism is inspiring.",
    "You have a way of making people feel important and valued.",
    "Your kindness is a true gift to those around you.",
    "Your confidence is magnetic.",
    "Your intelligence is truly impressive.",
    "Your resilience is remarkable.",
    "Your determination is unwavering.",
    "Your passion for life is inspiring.",
    "Your creativity is truly awe-inspiring.",
    "Your hard work is paying off in spades.",
    "Your loyalty is unwavering.",
    "Your attention to detail is truly remarkable.",
    "You have a unique perspective that is truly valuable.",
    "Your intuition is impressive.",
    "Your generosity knows no bounds.",
    "You have a natural talent for bringing people together.",
    "Your presence is truly uplifting.",
    "Your positive attitude is infectious.",
    "Your optimism is inspiring.",
    "You have a way of making people feel important and valued.",
    "Your kindness is a true gift to those around you.",
    "Your confidence is magnetic.",
    "Your intelligence is truly impressive.",
    "Your resilience is remarkable.",
    "Your determination is unwavering"
];

document.body.onload = function() {
    newCompliment();
};

document.body.onkeyup = function(e) {
    if (e.which == 32) {
        newCompliment();
    }
};

function newCompliment() {
    document.getElementById("compliment").innerHTML = window.compliments[Math.floor(Math.random() * window.compliments.length)];
}
